
CREATE TABLE DEPARTMENT (
	DEPT_ID NUMBER(2) NOT NULL,
	DEPT_NAME VARCHAR2(25) NOT NULL,
	INTAKE NUMBER(3) DEFAULT 60 NOT NULL,
	HEADED_BY NUMBER(3) DEFAULT 101,
	CONSTRAINT DEPARTMENT_PK_DEPT_ID PRIMARY KEY (DEPT_ID),
	CONSTRAINT DEPARTMENT_CK_INTAKE CHECK (INTAKE IN (30, 60, 120, 180))
);	

CREATE TABLE TEACHER (
	TEACHER_ID NUMBER(3) NOT NULL,
	FNAME VARCHAR2(15) NOT NULL,
	LNAME VARCHAR2(15) NOT NULL,
	DEPT_ID NUMBER(2) NOT NULL,
	GENDER CHAR(1) NOT NULL,
	BASIC_SAL NUMBER(8,2) DEFAULT 75000 NOT NULL,
	CONSTRAINT TEACHER_PK_TEACHER_ID PRIMARY KEY (TEACHER_ID),
	CONSTRAINT TEACHER_FK_DEPARTMENT_DEPT_ID FOREIGN KEY (DEPT_ID)
		REFERENCES DEPARTMENT(DEPT_ID),
	CONSTRAINT TEACHER_CK_GENDER CHECK (GENDER IN ('M', 'F', 'm', 'f'))
);

