start C:\Users\AaronRocque\Documents\V_Semester\Lab\DBMS\Practical-3\academic

DESC STUDENT

SELECT ROLL, FNAME, LNAME
	FROM STUDENT
	WHERE ROLL=31;
	
SELECT * FROM STUDENT;

SET PAGESIZE 50;
SET LINESIZE 200;

CREATE SEQUENCE TEST_SQ
	START WITH 11
	MAXVALUE 100
	MINVALUE 1
	NOCYCLE 
	ORDER
	NOCACHE;
	
SELECT * FROM TAB;
--Can't see in TAB

SELECT * FROM CAT;

SELECT OBJECT_NAME, OBJECT_TYPE
	FROM USER_OBJECTS
	WHERE OBJECT_NAME = 'TEST_SQ';
	
COLUMN OBJECT_NAME FORMAT A20

DESC USER_SEQUENCES 

COLUMN OBJECT_NAME FORMAT A20
COLUMN MIN_VALUE HEADING MNV FORMAT 999
COLUMN MAX_VALUE HEADING MXV FORMAT 999
COLUMN SEQUENCE_NAME HEADING SEQ_NAME FORMAT A12
COLUMN INCREMENT_BY HEADING INR FORMAT 999
COLUMN CACHE_SIZE HEADING CACHE FORMAT 99999
COLUMN LAST_NUMBER HEADING LAST FORMAT 999

SELECT * FROM USER_SEQUENCES 
	WHERE SEQUENCE_NAME = 'TEST_SQ';
	
SELECT TEST_SQ.CURRVAL FROM DUAL;
--Dual is a memory soace, a scratch pad

SELECT TEST_SQ.NEXTVAL FROM DUAL;

SELECT * FROM USER_SEQUENCES 
	WHERE SEQUENCE_NAME = 'TEST_SQ';
--LAST = 12

SELECT TEST_SQ.CURRVAL FROM DUAL;

CREATE TABLE 
	TT (ID NUMBER(3) NOT NULL PRIMARY KEY, AGE NUMBER(2)
		NOT NULL);
		
INSERT INTO TT VALUES (TEST_SQ.CURRVAL+90, 18);

INSERT INTO TT VALUES (TEST_SQ.NEXTVAL+90, 18);

INSERT INTO TT VALUES (TEST_SQ.NEXTVAL+90, 19);

INSERT INTO TT VALUES (TEST_SQ.NEXTVAL+90, 21);

COMMIT;

SELECT * FROM USER_SEQUENCES 
	WHERE SEQUENCE_NAME = 'TEST_SQ';
	
SELECT * FROM TT;

DROP SEQUENCE TEST_SQ;
--Delete

SELECT * FROM CAT;

--Views

DESC CUSTOMER

--CLONNING TABLE CUSTOMER
CREATE TABLE CUST AS SELECT * FROM CUSTOMER;

SELECT COUNT(*) FROM CUST;

ALTER TABLE CUST
	ADD CONSTRAINT 
	CUST_PK_C_CODE PRIMARY KEY (C_CODE);
	
SELECT * FROM CUST;

DESC CUST

ALTER TABLE CUST 
	MODIFY (C_PHONE NUMBER(7), BALANCE NUMBER(9,2)); 

DESC CUST

ALTER TABLE CUST 
	MODIFY C_PHONE NUMBER(7) NULL; 
	
ALTER TABLE CUST 
	MODIFY BALANCE NUMBER(9,2) NULL;
	
DESC CUST

CREATE OR REPLACE VIEW CUS_VW
	AS SELECT C_CODE, FNAME, LNAME, BALANCE	
		FROM CUST;
		
CONNECT SYSTEM/system

GRANT CREATE VIEW TO CS5A31;

CONNECT CS5A31/cs5a31

CREATE OR REPLACE VIEW CUS_VW
	AS SELECT C_CODE, FNAME, LNAME, BALANCE	
		FROM CUST;
		
--CHEECKING VIEW

DESC TAB

SELECT * FROM TAB
	WHERE TNAME = 'CUS_VW';
	
SELECT * FROM CAT
	WHERE TABLE_NAME = 'CUS_VW';

--DO THIS	
SELECT * FROM USER_OBJECTS
	WHERE OBJECTNAME = 'CUS_VW';
	
DESC USER_VIEWS

COLUMN VIEW_NAME FORMAT A15
COLUMN VIEW_TYPE FORMAT A15

SELECT VIEW_NAME, VIEW_TYPE, READ_ONLY 
	FROM USER_VIEWS
	WHERE UPPER(VIEW_NAME) LIKE '%VW%';
	
SELECT * FROM CUS_VW;

SHOW LONG 

COLUMN TEXT FORMAT A50

SELECT VIEW_NAME, TEXT 
	FROM USER_VIEWS
	WHERE UPPER(VIEW_NAME) LIKE '%VW%';
	
------------------------------------------------------------------
DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE STAFF CASCADE CONSTRAINTS;
DROP TABLE DEPT CASCADE CONSTRAINTS;
DROP SEQUENCE STAFF_SQ;
PURGE RECYCLEBIN;
------------------------------------------------------------------
Q1

start C:\Users\AaronRocque\Documents\V_Semester\Lab\DBMS\Practical-3\academic

COLUMN OBJECT_NAME FORMAT A20
COLUMN MIN_VALUE HEADING MNV FORMAT 999
COLUMN MAX_VALUE HEADING MXV FORMAT 999
COLUMN SEQUENCE_NAME HEADING SEQ_NAME FORMAT A12
COLUMN INCREMENT_BY HEADING INR FORMAT 999
COLUMN CACHE_SIZE HEADING CACHE FORMAT 99999
COLUMN LAST_NUMBER HEADING LAST FORMAT 999
COLUMN TEXT FORMAT A50
COLUMN VIEW_NAME FORMAT A15
COLUMN VIEW_TYPE FORMAT A15
SET PAGESIZE 100;
COLUMN FNAME FORMAT A10
COLUMN LNAME FORMAT A10
COLUMN ROLL FORMAT 999
COLUMN ADVISOR FORMAT 9999
COLUMN EMAIL FORMAT A10
SET LINESIZE 100;


SELECT * FROM STUDENT;

SELECT * FROM STAFF;

SELECT * FROM DEPT;

------------------------------------------------------------------

Q2

CREATE SEQUENCE STAFF_SQ
	START WITH 106
	MAXVALUE 200
	MINVALUE 100
	NOCYCLE 
	ORDER
	NOCACHE;

SELECT * FROM USER_SEQUENCES 
	WHERE SEQUENCE_NAME = 'STAFF_SQ';
	
SELECT * FROM STAFF;

SELECT STAFF_SQ.NEXTVAL FROM DUAL;

INSERT INTO STAFF 
	VALUES (STAFF_SQ.CURRVAL, 'Deo Narayan Mishra','DAT', 'Assistant', '13-Oct-2013');
	
INSERT INTO STAFF 
	VALUES (STAFF_SQ.CURRVAL+1, 'Sanjeev Bamireddy','CSEC', 'Associate', '12-May-2018');
	
INSERT INTO STAFF 
	VALUES (STAFF_SQ.NEXTVAL, 'Sanjeev Bamireddy','CSEC', 'Associate', '12-May-2018');
	
INSERT INTO STAFF 
	VALUES (STAFF_SQ.NEXTVAL, 'Jasmine Arora','CSE', 'Assistant', '11-Aug-2017');
	
INSERT INTO STAFF 
	VALUES (STAFF_SQ.NEXTVAL, 'Vallabh Pai','CSE', 'Assistant', '17-Sep-2018');
	
INSERT INTO STAFF 
	VALUES (STAFF_SQ.NEXTVAL, 'Harmeet Khullar', 'AIML', 'Assistant', '17-Mar-2019');
	
SELECT * FROM STAFF;

SELECT * FROM USER_SEQUENCES 
	WHERE SEQUENCE_NAME = 'STAFF_SQ';
	
DROP SEQUENCE STAFF_SQ;

------------------------------------------------------------------

Q3

SELECT ROLL, FNAME, LNAME, STAFF.NAME as Advisor_Name
	FROM STUDENT 
	JOIN STAFF 
	ON STUDENT.ADVISOR = STAFF.SID
	WHERE ROLL = 31;

------------------------------------------------------------------


Q4

SELECT CONSTRAINT_NAME, TABLE_NAME 
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME 
IN ('STUDENT','STAFF', 'DEPT');

ALTER TABLE STUDENT
ADD CONSTRAINT STUDENT_FK_STAFF_SID
FOREIGN KEY(ADVISOR) REFERENCES STAFF(SID);

SELECT CONSTRAINT_NAME, TABLE_NAME 
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME 
IN 'STUDENT';
------------------------------------------------------------------


Q5

CREATE OR REPLACE VIEW STUDENT_VW
AS SELECT ENROLL, LNAME, FNAME, ROLL, REG_DT, ADVISOR
FROM STUDENT;

SELECT * FROM TAB 
WHERE TNAME='STUDENT_VW';

SELECT * FROM CAT
WHERE TABLE_NAME = 'STUDENT_VW';
	
SELECT * FROM STUDENT_VW;

------------------------------------------------------------------


Q6

INSERT INTO STUDENT_VW VALUES 
('21CSU1231CSU1', 'Namjoshi', 'Navin', 81, '13-NOV-2021',109);

INSERT INTO STUDENT_VW VALUES 
('21CSU1232CSU1', 'Tipnis', 'Tushar', 82, '13-NOV-2021',110);

SELECT * FROM STUDENT_VW
WHERE ROLL = 81 OR ROLL = 82;

COLUMN FNAME FORMAT A10
COLUMN LNAME FORMAT A10
COLUMN ROLL FORMAT 999
COLUMN ADVISOR FORMAT 9999
COLUMN EMAIL FORMAT A10

SELECT * FROM STUDENT
WHERE ROLL = 81 OR ROLL = 82;
------------------------------------------------------------------


Q7

CREATE OR REPLACE VIEW STUDENT_VW_RO
AS SELECT ENROLL, LNAME, FNAME, ROLL, REG_DT, ADVISOR
FROM STUDENT
WITH READ ONLY;

SELECT * FROM CAT
WHERE TABLE_NAME = 'STUDENT_VW_RO';

SELECT * FROM STUDENT_VW_RO;

INSERT INTO STUDENT_VW_RO VALUES 
('21CSU1233CSU1', 'Cindrella', 'Goldsmith', 83, '17-NOV-2021',101);

------------------------------------------------------------------


Q8

CREATE OR REPLACE VIEW STUDENT_VW_CK
AS SELECT ENROLL, LNAME, FNAME, ROLL, REG_DT, ADVISOR
FROM STUDENT
WHERE ADVISOR IN (101,103, 105, 108, 109)
WITH CHECK OPTION CONSTRAINT STUDENT_ADV_CK;

SELECT * FROM STUDENT_VW_CK;

INSERT INTO STUDENT_VW_CK VALUES
('21CSU1234CSU1', 'Sebastian', 'Ford', 84, '18-NOV-2021',104);


------------------------------------------------------------------


Q9

SELECT VIEW_NAME, VIEW_TYPE, READ_ONLY 
FROM USER_VIEWS
WHERE VIEW_NAME LIKE 'STUDENT_VW%'
OR VIEW_NAME LIKE 'STAFF_VW%'
OR VIEW_NAME LIKE 'DEPT_VW%';

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'STUDENT_VW%'
OR TABLE_NAME LIKE 'STAFF_VW%'
OR TABLE_NAME LIKE 'DEPT_VW%';

------------------------------------------------------------------

Q10

CREATE OR REPLACE SYNONYM FACULTY_SN
FOR STAFF;

SELECT SYNONYM_NAME, TABLE_NAME FROM USER_SYNONYMS
WHERE SYNONYM_NAME='FACULTY_SN';

SELECT * FROM FACULTY_SN;

INSERT INTO FACULTY_SN VALUES
(111,'Dhawal Giri', 'AIML','Assistant', '25-SEP-2022');

SELECT * FROM FACULTY_SN;

SELECT * FROM STAFF;

	
------------------------------------------------------------------


Q11

CREATE UNIQUE INDEX STUDENT_NDX_FNAME_UQ
ON STUDENT(FNAME);

CREATE INDEX STUDENT_NDX_FNAME
ON STUDENT(FNAME);

SET AUTOTRACE ON EXPLAIN
SHOW AUTOTRACE

SELECT * FROM STUDENT 
WHERE FNAME='Aaron';

CREATE UNIQUE INDEX STUDENT_NDX_FNAME_LNAME_UQ
ON STUDENT(FNAME, LNAME);

COLUMN TABLE_OWNER FORMAT A10

SELECT INDEX_NAME, TABLE_NAME, UNIQUENESS, STATUS, TABLE_OWNER
FROM USER_INDEXES
WHERE TABLE_NAME IN ('STUDENT', 'STAFF', 'DEPT')
AND TABLE_OWNER ='CS5A31';

SELECT * FROM STUDENT
WHERE FNAME='Aaron' AND LNAME='Rocque';

------------------------------------------------------------------


Q12

CONNECT SYSTEM/system

ALTER SYSTEM SET QUERY_REWRITE_ENABLED = TRUE;

CONNECT CS5A31/cs5a31

CREATE INDEX STUDENT_NDX_LNAME_FN
ON STUDENT(UPPER(LNAME));

SELECT * FROM STUDENT 
WHERE UPPER(LNAME) ='ROCQUE';

CREATE INDEX STUDENT_NDX_LNAME_FNAME_FN
ON STUDENT(UPPER(LNAME),UPPER(FNAME));

SELECT * FROM STUDENT 
WHERE UPPER(LNAME) ='ROCQUE' AND UPPER(FNAME)='AARON';

SET AUTOTRACE OFF EXPLAIN

------------------------------------------------------------------

Q13

SAVEPOINT SP_NONE;

INSERT INTO STUDENT VALUES 
	(83, 'Goldsmith', 'Cindrella', 'goldsmithc@rknec.edu', '21CSU1233CSU1', 101, 1112223334, '17-NOV-2021');

INSERT INTO STUDENT VALUES 
	(84, 'Ford', 'Sebastian', 'fords@rknec.edu', '21CSU1234CSU1', 104, 5556667778, '18-NOV-2021');

SELECT * FROM STUDENT 
	WHERE ROLL IN(83,84);

SAVEPOINT SP_FORD;

UPDATE STUDENT
SET ADVISOR = 108
WHERE FNAME='Navin' AND LNAME='Namjoshi';

SELECT * FROM STUDENT 
WHERE FNAME='Navin' AND LNAME='Namjoshi';

SAVEPOINT SP_NAV;

UPDATE STUDENT
SET ADVISOR = 111
WHERE FNAME='Tushar' AND LNAME='Tipnis';

SELECT * FROM STUDENT 
WHERE FNAME='Tushar' AND LNAME='Tipnis';

SAVEPOINT SP_TUS;
------------------------------------------------------------------

Q14

ROLLBACK TO SP_FORD;

SELECT * FROM STUDENT 
WHERE ROLL IN(83,84);

SELECT * FROM STUDENT 
WHERE FNAME='Navin' AND LNAME='Namjoshi';

SELECT * FROM STUDENT 
WHERE FNAME='Tushar' AND LNAME='Tipnis';

ROLLBACK TO SP_NONE;

SELECT * FROM STUDENT 
WHERE ROLL IN(83,84);

SELECT * FROM STUDENT 
WHERE FNAME='Navin' AND LNAME='Namjoshi';

SELECT * FROM STUDENT 
WHERE FNAME='Tushar' AND LNAME='Tipnis';

------------------------------------------------------------------

DELETE FROM STUDENT 
WHERE ROLL IN(83,84);

UPDATE STUDENT
SET ADVISOR = 109
WHERE FNAME='Navin' AND LNAME='Namjoshi';

SELECT * FROM STUDENT 
WHERE FNAME='Navin' AND LNAME='Namjoshi';

UPDATE STUDENT
SET ADVISOR = 110
WHERE FNAME='Tushar' AND LNAME='Tipnis';

SELECT * FROM STUDENT 
WHERE FNAME='Tushar' AND LNAME='Tipnis';