/*
Script Name: "oracleDemo.sql"
============================
    This script create a database user account named TEST and assigns required
    set of privileges and permissions to the user created.
    
    AUTHOR      : PROF. D. A. BORIKAR
    AFFILIATION : CSE, RCOEM NAGPUR
    DATE WRITTEN: 03-SEP-2022
    
NOTE: Strictly for use within RCOEM Nagpur for CSP351. Not to be circulated.
*/
-- CREATE USER AND ASSIGN PREVILEGES
CONNECT SYSTEM/system
DROP USER TEST CASCADE;
CREATE USER TEST IDENTIFIED BY test QUOTA 100M ON USERS;
GRANT CONNECT,RESOURCE TO TEST;
CONNECT TEST/test

SET ECHO OFF
SET FEEDBACK OFF
SET VERIFY OFF
SET PAGESIZE 25
SET LINESIZE 80

DROP TABLE TEACHER CASCADE CONSTRAINTS PURGE;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS PURGE;
CLEAR SCR;

PROMPT CREATING DATABASE TABLES..

CREATE TABLE DEPARTMENT (
    DEPT_ID NUMBER(2) NOT NULL,
    DEPT_NAME VARCHAR2(25) NOT NULL,
    INTAKE NUMBER(3) DEFAULT 60 NOT NULL,
    HEADED_BY NUMBER(3) DEFAULT 101 NOT NULL,
    CONSTRAINT DEPARTMENT_PK_DEPT_ID PRIMARY KEY (DEPT_ID),
    CONSTRAINT DEPARTMENT_CK_INTAKE CHECK (INTAKE IN (30,60,120,180))
);


CREATE TABLE TEACHER (
    TEACHER_ID NUMBER(3) NOT NULL,
    FNAME VARCHAR2(15) NOT NULL,
    LNAME VARCHAR2(15) NOT NULL,
    DEPT_ID NUMBER(2) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    BASIC_SAL NUMBER(8,2) DEFAULT 75000 NOT NULL,
    CONSTRAINT TEACHER_PK_TEACHER_ID PRIMARY KEY (TEACHER_ID),
    CONSTRAINT TEACHER_FK_DEPARTMENT_DEPT_ID FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT(DEPT_ID),
    CONSTRAINT TEACHER_CK_GENDER CHECK (GENDER IN ('M','F','m','f'))
);

PROMPT POPULATING TABLES
-- DEPARTMENT
INSERT INTO DEPARTMENT VALUES (11,'COMPUTER SCIENCE ENGG',180,101);
INSERT INTO DEPARTMENT VALUES (22,'ELECTRONICS ENGG',120,101);

-- TEACHER
INSERT INTO TEACHER VALUES (101,'Sanchit','Sinha',11,'M',80000);
INSERT INTO TEACHER VALUES (102,'Preeti','Batra',22,'F',90000);
INSERT INTO TEACHER VALUES (103,'Vishwa','Bhargav',22,'M',70000);
COMMIT;

-- ENFORCE ADDITIONAL CONSTRAINTS
ALTER TABLE DEPARTMENT
    ADD CONSTRAINT DEPT_FK_TEACHER_HEADED_BY FOREIGN KEY (HEADED_BY)
        REFERENCES TEACHER(TEACHER_ID);

PROMPT DATABASE CREATED AND POPULATED
PROMPT
SET FEEDBACK 1
SET VERIFY ON
SET ECHO ON
SELECT * FROM DEPARTMENT;
SELECT * FROM TEACHER;
SHOW USER
