/*
CURSOR
	
	Two types:
	1. Implicit
		Automatically declared
		SQL statement is executed
		Not under USER's control
		(NOTE: SQL Cursor is the most recently used cursor)
		Parameter: SQL%ROWCOUNT
			You will know how many rows are returned by the cursor.
	2. Explicit
		Program defines it and returns more than one row of data.
		Prorammers Control: Declare, Execute [Open, Fetch, Close]
		

*/

ALTER TABLE PERSON
	ADD(STATUS CHAR(5));
	
DESC PERSON;

SET SERVEROUTPUT ON

--Implicit Cursor
BEGIN 
	UPDATE PERSON
		SET STATUS = 'TRUE';
	DBMS_OUTPUT.PUT_LINE('Rows Affected := '||SQL%ROWCOUNT);
END;
/

--Declaring Exlicit CURSOR
DECLARE 
	CURSOR C_PERSON_DETAILS IS	
		SELECT FNAME, LNAME, STATUS	
			FROM PERSON
			WHERE BIRTHDATE <'01-JAN-2005';
	PERSON_REC C_PERSON_DETAILS%ROWTYPE;
	
	BEGIN 
		OPEN C_PERSON_DETAILS;
		LOOP	
			FETCH C_PERSON_DETAILS INTO PERSON_REC;
				EXIT WHEN C_PERSON_DETAILS%NOTFOUND;
			DBMS_OUTPUT.PUT_LINE(PERSON_REC.FNAME||' '||PERSON_REC.LNAME||' '||PERSON_REC.STATUS);
		END LOOP;
		CLOSE C_PERSON_DETAILS;
		DBMS_OUTPUT.PUT_LINE(CHR(10));
		DBMS_OUTPUT.PUT_LINE('CURSOR PROCESSED');
	END;
/

DECLARE 
	CURSOR C_PERSON_DETAILS IS	
		SELECT FNAME, LNAME, STATUS	
			FROM PERSON
			WHERE BIRTHDATE <'01-JAN-2005';
	PERSON_REC C_PERSON_DETAILS%ROWTYPE;
	
	BEGIN 
		OPEN C_PERSON_DETAILS;
		LOOP	
			FETCH C_PERSON_DETAILS INTO PERSON_REC;
				EXIT WHEN C_PERSON_DETAILS%NOTFOUND;
			DBMS_OUTPUT.PUT_LINE(PERSON_REC.FNAME||' '||PERSON_REC.LNAME||' '||PERSON_REC.STATUS);
		END LOOP;
		CLOSE C_PERSON_DETAILS;
		DBMS_OUTPUT.PUT_LINE(CHR(10));
		DBMS_OUTPUT.PUT_LINE('CURSOR PROCESSED');
		
	EXCEPTION
		WHEN OTHERS THEN
			IF C_PERSON_DETAILS%ISOPEN THEN	
				DBMS_OUTPUT.PUT_LINE('CLOSING THE CURSOR...');
				CLOSE C_PERSON_DETAILS;
			END IF;
	END;
/

DECLARE 
	CURSOR C_PERSON_DETAILS IS	
		SELECT FNAME, LNAME, GENDER	
			FROM PERSON;
	
	BEGIN 
		FOR PERSON_REC IN C_PERSON_DETAILS
			LOOP	
				FETCH C_PERSON_DETAILS INTO PERSON_REC;
					EXIT WHEN C_PERSON_DETAILS%NOTFOUND;
				DBMS_OUTPUT.PUT_LINE(PERSON_REC.FNAME||' '||PERSON_REC.LNAME||' '||PERSON_REC.GENDER);
			END LOOP;
		DBMS_OUTPUT.PUT_LINE(CHR(10));
		DBMS_OUTPUT.PUT_LINE('CURSOR PROCESSED');
		
	END;
/
--ERROR


	


-----------

CREATE OR REPLACE PROCEDURE SHOW_ITEM_TMR_E(V_P_CODE ITEM.P_CODE%TYPE)
AS
V_DATA ITEM%ROWTYPE;
BEGIN
SELECT * INTO V_DATA
FROM ITEM
WHERE P_CODE = V_P_CODE ;
DBMS_OUTPUT.PUT_LINE(RPAD(V_DATA.P_CODE,8) || RPAD(V_DATA.DESCR,20) || 
RPAD(V_DATA.IN_DATE,8) || RPAD(V_DATA.MIN_QTY,4) ||RPAD(V_DATA.QTY,8) 
 ||RPAD(V_DATA.PRICE,8) );
EXCEPTION
WHEN TOO_MANY_ROWS THEN
DBMS_OUTPUT.PUT_LINE(V_P_CODE ||' MULTIPLE ROWS .........');
END;
/
